In [1]:
import pandas as pd

### ReceitasMinerão2014-2025

In [3]:
df = pd.DataFrame()
df = pd.read_csv('../data.csv/receitas_mineirao_2014_2022.csv')
df

,Ano,receita_ingresso,receita_produtos_internos,data,times_que_jogaram,classificacao_para_competicao,total_arrecadado
0,2017,183179.15,35041.19,2017-07-29,Cruzeiro vs Atlético-MG,não,218220.34
1,2018,180623.99,23812.53,2018-10-18,Cruzeiro vs Avaí,sim - copa libertadores,204436.52
2,2015,151581.28,27346.54,2015-12-05,Cruzeiro vs São Paulo,sim - qualificatória da copa libertadores,178927.82
3,2015,118258.47,20007.70,2015-09-28,Cruzeiro vs Atlético-MG,sim - qualificatória da copa libertadores,138266.17
4,2014,127956.58,24163.02,2014-01-27,Cruzeiro vs Palmeiras,não,152119.60
...,...,...,...,...,...,...,...
214,2020,116607.06,21061.39,2020-07-20,Cruzeiro vs CSA,sim - qualificatória da copa libertadores,137668.45
215,2015,145063.13,16107.79,2015-01-17,Cruzeiro vs CSA,não,161170.92
216,2022,79391.88,14131.30,2022-11-17,Cruzeiro vs CSA,não,93523.18
217,2019,118346.74,15535.81,2019-08-19,Cruzeiro vs Botafogo,não,132882.55
218,2018,117327.36,10689.15,2018-08-17,Cruzeiro vs Fluminense,não,128016.51

In [ ]:
df = pd.DataFrame()
df = pd.read_csv('../data.csv/perfil_demografico_torcida.csv')
df[df['Tipo_Metrica'] == 'Gênero']

,Jogo_ID,Competição,Público_Total_Jogo,Clube,Tipo_Metrica,Categoria,Valor_Percentual,Valor_Nominal
0,JOGO_1,Brasileirão,26557,CRUZEIRO,Gênero,MASCULINO,65%,15536
1,JOGO_1,Brasileirão,26557,CRUZEIRO,Gênero,FEMININO,35%,8365
2,JOGO_1,Brasileirão,26557,BAHIA,Gênero,MASCULINO,60%,1594
3,JOGO_1,Brasileirão,26557,BAHIA,Gênero,FEMININO,40%,1062
23,JOGO_2,Mineiro,47036,ATLÉTICO,Gênero,MASCULINO,70%,16462
24,JOGO_2,Mineiro,47036,ATLÉTICO,Gênero,FEMININO,30%,7056
25,JOGO_2,Mineiro,47036,AMÉRICA,Gênero,MASCULINO,65%,15287
26,JOGO_2,Mineiro,47036,AMÉRICA,Gênero,FEMININO,35%,8231
45,JOGO_3,Copa do Brasil,61583,CRUZEIRO,Gênero,MASCULINO,75%,46187
46,JOGO_3,Copa do Brasil,61583,CRUZEIRO,Gênero,FEMININO,25%,15396